
###get all users
GET http://localhost:3000/server/users

###get all products
GET http://localhost:3000/server/api

###get category
GET http://localhost:3000/server/api/filter?category=semipreciousStones


### login
POST http://localhost:3000/server/auth/login
Content-Type: application/json

{
    "login":"sas",
    "password":"sas"
}


### check token
POST http://localhost:3000/server/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InNhcyIsInN1YiI6IjQxY2QwMTZmLTdhYjQtNDc5NS1iYmY0LWZmZmRmYmRkNDdlMCIsInJvbCI6InVzZXIiLCJ0eXBlIjoiQUNDRVNTX1RPS0VOIiwiaWF0IjoxNTc3MzA0NzcwLCJleHAiOjE1NzczMDY1NzB9.hYc59-VyEP0sCjFigQjZ8qNVUd2k3iOGVtxVpWgJOyw

### refresh token

PUT http://localhost:3000//server/transactions/buy
Content-Type: application/json
{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InNhcyIsInN1YiI6IjQxY2QwMTZmLTdhYjQtNDc5NS1iYmY0LWZmZmRmYmRkNDdlMCIsInJvbCI6InVzZXIiLCJ0eXBlIjoiUkVGUkVTSF9UT0tFTiIsImlhdCI6MTU3NzMwNTk2MywiZXhwIjoxNTc3MzA3NzYzfQ.XD5I28sa-wCe-mucC7hyIhsK-lOdaZZLF3jWO6MnH04"
}

### buy
POST http://localhost:3000/server/transactions/buy
Content-Type: application/json
{
	{
			"products":[
				{
					"id":"613bd89f-d862-444a-a03f-7d8479791179",
					"count":1
				}
				],
			"adress":"dsfsdf",
			"fulName":"krzysio",
			"mail":"dfd"
}
}
